// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantGuide.Models;

namespace RestaurantGuide.Migrations
{
    [DbContext(typeof(RestaurantGuideContext))]
    [Migration("20191029172039_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RestaurantGuide.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Cuisine");

                    b.Property<string>("Name");

                    b.Property<string>("Neighborhood");

                    b.Property<string>("Quadrant");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Address = "123 Fake St",
                            Cuisine = "Thai BBQ",
                            Name = "Eem",
                            Neighborhood = "Boise",
                            Quadrant = "NE"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Address = "124 Fake St.",
                            Cuisine = "Pizza",
                            Name = "Ken's Artisan Pizza",
                            Neighborhood = "Kerns",
                            Quadrant = "SE"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Address = "125 Fake St.",
                            Cuisine = "Italian",
                            Name = "Serratto",
                            Neighborhood = "Nob Hill",
                            Quadrant = "NW"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
